<?php

enum EpsEnum: string{
    case COOSALUD ="COOSALUD EPS-S";
    case NUEVA_EPS ="NUEVA EPS";
    case MUTUAL_SER ="MUTUAL SER";
    case ALIANSALUD_EPS ="ALIANSALUD EPS";
    case SALUD_TOTAL ="SALUD TOTAL EPS S.A.";
    case SANITAS ="EPS SANITAS";
    case SURA ="EPS SURA";
    case FAMISANAR ="FAMISANAR";
    case SOS ="SERVICIO OCCIDENTAL DE SALUD EPS SOS";
    case SALUD_MIA ="SALUD MIA";
    case COMFENALCO="COMFENALCO VALLE";
    case COMPENSAR="COMPENSAR EPS";
    case EPM ="EPM - EMPRESAS PUBLICAS DE MEDELLIN";
    case FPSFNC ="FONDO DE PASIVO SOCIAL DE FERROCARRILES NACIONALES DE COLOMB";
    case CAJACOPI_ATLANTICO="CAJACOPI ATLANTICO";
    case CAPRESOCA="CAPRESOCA";
    case COMFACHOCO="COMFACHOCO";
    case COMFAMILIAR="COMFAMILIAR DE LA  GUAJIRA";
    case COMFAORIENTE="COMFAORIENTE";
    case FAMILIAR_COLOMBIA="EPS FAMILIAR DE COLOMBIA (Antes ComfaSucre)";
    case ASMET_SALUD="ASMET SALUD";
    case ECOOPSOS="ECOOPSOS ESS EPS-S";
    case EMSSANAR="EMSSANAR E.S.S.";
    case CAPITAL_SALUD="CAPITAL SALUD EPS-S";
    case SAVIA_SALUD="SAVIA SALUD EPS";
    case DUSAKAWI="DUSAKAWI EPSI";
    case AIC_EPSI="ASOCIACION INDIGENA DEL CAUCA EPSI";
    case ANAS_WAYUU ="ANAS WAYUU EPSI";
    case MALLAMAS="MALLAMAS EPSI";
    case PIJAOS_SALUD="PIJAOS SALUD EPSI";    
};